// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate deploy, migrate dev, studio) necesita la conexión
    // DIRECTA (sin pooler) — sobre una conexión pooled, el motor de
    // migraciones puede fallar por los advisory locks / prepared statements
    // que usa. DATABASE_URL (pooled) queda reservado para el cliente en
    // runtime (src/lib/db.ts), que no pasa por este archivo. El fallback a
    // DATABASE_URL cubre el desarrollo local con una única base sin
    // distinción pooled/directa (ej. `prisma dev`), donde DIRECT_URL no
    // existe.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
